name: رفع فيديوهات YouTube Shorts تلقائي مع فرق زمني

on:
  schedule:
    - cron: '0 */3 * * *'  # كل 3 ساعات تقريبًا
  workflow_dispatch:  # للتشغيل اليدوي عند الحاجة
  push:
    paths:
      - 'videos/**'

jobs:
  upload:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v3

      - name: Setup Python
        uses: actions/setup-python@v4
        with:
          python-version: '3.11'

      - name: تثبيت المكتبات المطلوبة
        run: |
          pip install --upgrade pip
          pip install google-api-python-client google-auth-httplib2 google-auth-oauthlib

   

      - name: تشغيل بوت رفع الفيديوهات
        run: |
          python upload_bot.py
